* Project Isidore
#+html: <a href="https://github.com/HanshenWang/project-isidore/releases/"><img src="https://img.shields.io/github/v/release/HanshenWang/project-isidore"/></a></br>
#+html: <a href="https://project-isidore.herokuapp.com/"><img src="https://pyheroku-badge.herokuapp.com/?app=project-isidore"/></a>
[[https://github.com/HanshenWang/project-isidore/actions/workflows/CICD.yml][https://github.com/HanshenWang/project-isidore/actions/workflows/CICD.yml/badge.svg?branch=master]]

The third iteration of my personal website. It was quite fun building this with
Common Lisp. Happy Hacking!

Copyright (c) 2021 Hanshen Wang. Source code is under the [[https://www.gnu.org/licenses/agpl-3.0-standalone.html][GNU-AGPL-3.0 License]].
Blog content is available under the [[https://creativecommons.org/licenses/by-sa/4.0/legalcode][CC-BY-SA 4.0 License]] unless otherwise noted.

** Development Quick Start

Prerequisite(s):

An ANSI Common Lisp implementation. Development platform is x86_64 GNU/Linux with [[http://www.sbcl.org/][SBCL.]]

The [[https://www.quicklisp.org/beta/][Quicklisp]] library manager to download system dependencies.

*Optionally,* a local installation of [[https://www.postgresql.org/][PostgreSQL.]]

1. Clone the repository

   #+begin_src bash
   cd ~/quicklisp/local-projects
   git clone https://github.com/HanshenWang/project-isidore.git
   #+end_src

2. Within [[https://www.gnu.org/software/emacs/][Emacs]], start a Common Lisp IDE ([[https://github.com/joaotavora/sly][SLY]]) buffer with =M-x sly=. Depending
   on the current working directory, =M-x sly-mrepl-set-directory= to Project
   Isidore root directory may be needed. [[https://lispcookbook.github.io/cl-cookbook/editor-support.html#vscode][Non-Emacs Common Lisp IDE options.]]

3. Load Project Isidore & start local development server.

   #+begin_src lisp
     (ql:quickload :project-isidore)
     (in-package :project-isidore) ; switch to package namespace
     (initialize-application) ; starts server at http://localhost:8080
     (terminate-application) ; stop server
   #+end_src

Full documentation available here:
https://www.hanshenwang.com/blog/project-isidore-doc.html

[[https://develop.spacemacs.org][file:https://cdn.rawgit.com/syl20bnr/spacemacs/442d025779da2f62fc86c2082703697714db6514/assets/spacemacs-badge.svg]]
