# Continous Delivery.yml
#
# Copyright (c) 2021 Hanshen Wang.
#
# Author: Hanshen Wang <Hanshen@HanshenWang.com>
# URL: https://github.com/HanshenWang/project-isidore
#
# This file is part of Project Isidore.
#
# Project Isidore is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Project Isidore is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Project Isidore.  If not, see <https://www.gnu.org/licenses/>.

name: CD

# Controls when the action will run. Triggers the workflow upon tags 'v*.*.*'
# OR Trigger workflow manually through Github Actions repo website
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_executable_linux:
    name: Build on GNU/Linux
    runs-on: [ubuntu-latest]

    steps:
    # Check out your repository under $GITHUB_WORKSPACE, so your job can access it
    # $GITHUB_WORKSPACE may vary under $MATRIX.OS
    - uses: actions/checkout@v2

    - name: Cache .roswell
      id: cache-dot-roswell
      uses: actions/cache@v1
      with:
        path: ~/.roswell
        key: ${{ runner.os }}-dot-roswell-sbcl-bin-${{ hashFiles('**/*.asd') }}
        restore-keys: |
          ${{ runner.os }}-dot-roswell-sbcl-bin-
          ${{ runner.os }}-dot-roswell-

    - name: Install Roswell
      # always run install, since it does some global installs and setup that isn't cached
      env:
       LISP: sbcl-bin
      run: curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh -x

    - name: Run Lisp
      continue-on-error: true
      shell: bash
      run: |
        ros -e '(format t "~a:~a on ~a~%...~%~%" (lisp-implementation-type) (lisp-implementation-version) (machine-type))'
        ros -e '(format t " fixnum bits:~a~%" (integer-length most-positive-fixnum))'
        ros -e "(ql:quickload 'trivial-features)" -e '(format t "features = ~s~%" *features*)'

    - name: Update Quicklisp distribution if cached
      shell: bash
      run: ros -e "(ql:update-all-dists :prompt nil)"

    - name: Build Project Isidore
      shell: bash
      run: |
           echo ${{ github.workspace }} # Pathname varies amongst OS
           # Generates 'lispapp' in bin/ folder
           sudo ros build ProjectIsidore.ros

    # Github current policy is to retain logs and artifacts for 90 days.
    - name: GNU/Linux Upload Lisp Exectuable Artifact
      uses: actions/upload-artifact@v2
      with:
        name: pi-build-Linux
        path: |
          ${{ github.workspace }}/ProjectIsidore
          ${{ github.workspace }}/assets/
          ${{ github.workspace }}/LICENSE

  build_executable_macOS:
    name: Build on MacOS
    runs-on: [macos-latest]

    steps:
    # Check out your repository under $GITHUB_WORKSPACE, so your job can access it
    # $GITHUB_WORKSPACE may vary under $MATRIX.OS
    - uses: actions/checkout@v2

    - name: Cache .roswell
      id: cache-dot-roswell
      uses: actions/cache@v1
      with:
        path: ~/.roswell
        key: ${{ runner.os }}-dot-roswell-sbcl-bin-${{ hashFiles('**/*.asd') }}
        restore-keys: |
          ${{ runner.os }}-dot-roswell-sbcl-bin-
          ${{ runner.os }}-dot-roswell-

    - name: Install Roswell
      # always run install, since it does some global installs and setup that isn't cached
      env:
       LISP: sbcl-bin
      run: curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh -x

    - name: Run Lisp
      continue-on-error: true
      shell: bash
      run: |
        ros -e '(format t "~a:~a on ~a~%...~%~%" (lisp-implementation-type) (lisp-implementation-version) (machine-type))'
        ros -e '(format t " fixnum bits:~a~%" (integer-length most-positive-fixnum))'
        ros -e "(ql:quickload 'trivial-features)" -e '(format t "features = ~s~%" *features*)'

    - name: Update Quicklisp distribution if cached
      shell: bash
      run: ros -e "(ql:update-all-dists :prompt nil)"

    - name: Build Project Isidore
      shell: bash
      run: |
           echo ${{ github.workspace }} # Pathname varies amongst OS
           sudo ros build ProjectIsidore.ros

    # Github current policy is to retain logs and artifacts for 90 days.
    - name: MacOS Upload Lisp Exectuable Artifact
      uses: actions/upload-artifact@v2
      with:
        name: pi-build-macOS
        path: |
          ${{ github.workspace }}/ProjectIsidore
          ${{ github.workspace }}/assets/
          ${{ github.workspace }}/LICENSE

  build_executable_windows:
    name: Build on MSWindows
    runs-on: [windows-latest]

    steps:
    # Tell git not to convert line endings. Change roswell install dir and add it to path.
    - name: Setup Windows Environment
      run: |
        git config --global core.autocrlf false
        echo "ROSWELL_INSTALL_DIR=$HOME/ros" >> $GITHUB_ENV
        echo "$HOME/ros/bin" >> $GITHUB_PATH

    # Check out your repository under $GITHUB_WORKSPACE, so your job can access it
    # $GITHUB_WORKSPACE may vary under $MATRIX.OS
    - uses: actions/checkout@v2

    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        path-type: inherit
        release: true
        update: true
        install: 'base-devel mingw-w64-x86_64-toolchain p7zip'

    - name: Run MSYS2 once
      shell: msys2 {0}
      run: |
        pwd
        echo $MSYSTEM
        echo $MSYS2_PATH_TYPE
        echo $PATH

    - name: Cache .roswell
      id: cache-dot-roswell
      uses: actions/cache@v1
      with:
        path: ~/.roswell
        key: ${{ runner.os }}-dot-roswell-${{ matrix.lisp }}-${{ hashFiles('**/*.asd') }}
        restore-keys: |
          ${{ runner.os }}-dot-roswell-${{ matrix.lisp }}-
          ${{ runner.os }}-dot-roswell-

    - name: Install Roswell
      # always run install, since it does some global installs and setup that isn't cached
      shell: msys2 {0}
      env:
       LISP: sbcl-bin
      run: curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh -x

    - name: Build Project Isidore
      shell: msys2 {0}
      run: |
           echo ${{ github.workspace }}
           ros build ProjectIsidore.ros

    - name: MSWindows Upload Lisp Exectuable Artifact
      uses: actions/upload-artifact@v2
      with:
        name: pi-build-Windows
        path: |
          # NOTE THE .EXE REQUIRED FOR WINDOWS BUILDS
          ${{ github.workspace }}/ProjectIsidore.exe
          ${{ github.workspace }}/assets/
          ${{ github.workspace }}/LICENSE