# Continous Integration.yml
#
# Copyright (c) 2021 Hanshen Wang.
#
# Author: Hanshen Wang <Hanshen@HanshenWang.com>
# URL: https://github.com/HanshenWang/project-isidore
#
# This file is part of Project Isidore.
#
# Project Isidore is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Project Isidore is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Project Isidore.  If not, see <https://www.gnu.org/licenses/>.

name: CI

# Controls when the action will run. Triggers the workflow on push for any branch, and
# pull requests to master
on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin, ccl-bin]
        os: [ubuntu-latest, macos-latest]

    # run the job on every combination of "lisp" and "os" above
    runs-on: ${{ matrix.os }}

    steps:
    # Check out your repository under $GITHUB_WORKSPACE, so your job can access it
    # $GITHUB_WORKSPACE may vary under $MATRIX.OS
    - uses: actions/checkout@v2

    - name: Cache .roswell
      id: cache-dot-roswell
      uses: actions/cache@v1
      with:
        path: ~/.roswell
        key: ${{ runner.os }}-dot-roswell-${{ matrix.lisp }}-${{ hashFiles('**/*.asd') }}
        restore-keys: |
          ${{ runner.os }}-dot-roswell-${{ matrix.lisp }}-
          ${{ runner.os }}-dot-roswell-

    - name: Install Roswell
      # always run install, since it does some global installs and setup that isn't cached
      shell: bash
      env:
       LISP: ${{ matrix.lisp }}
      run: curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh -x

    - name: Install Parachute
      shell: bash
      run: |
        ros install parachute
        echo "$HOME/.roswell/bin" >> $GITHUB_PATH

    - name: Run Lisp
      continue-on-error: true
      shell: bash
      run: |
        ros -e '(format t "~a:~a on ~a~%...~%~%" (lisp-implementation-type) (lisp-implementation-version) (machine-type))'
        ros -e '(format t " fixnum bits:~a~%" (integer-length most-positive-fixnum))'
        ros -e "(ql:quickload 'trivial-features)" -e '(format t "features = ~s~%" *features*)'

    - name: Update Quicklisp distribution if cached
      shell: bash
      run: ros -e "(ql:update-all-dists :prompt nil)"

    - name: Load code and run tests
      shell: bash
      run: |
        run-parachute -l "project-isidore/test" "project-isidore/test"
